### ISSUE TITLE
Watch variable write access

### ISSUE THREAD

**Issue by theforcedk** [zorgiepoo/Bit-Slicer#10]
Hi there

What are the conditions for the "Watch variable write access" feature to work? It works on some addresses i look up, but not all. I'm trying to figure out what is writing to eg:

0000000103df80d8         db  0x00 ; '.'

There's no XREF def. on this line.

**Comment by zorgiepoo** [comment]
It triggers when the target executes an instruction that writes to the address you're watching.

Two edge cases I can think of it not working:

1. Since Bit Slicer does this by watching accesses on every thread of the process, new threads may be created later after you begin watching. As a simple workaround, Bit Slicer polls and fetches an updated thread list every short interval, but this may not catch some cases. This could be improved in the future..

2. When the process writes to the address in an indirect way, say through the kernel (e.g., mach_vm_write, memory allocation related functions).

Or there is the case that nothing is writing to it, but that can be somewhat verifiable by adding a variable with its address to a search window.

**Comment by theforcedk** [comment]
Makes sense. This is on Heroes of the Storm; Blizzard is sneaky, so you might be right.

Here are the two addresses if you have the game/play/whatever:

ulong BLUE_TEAM_LEVEL_PTR = 0x103DF80D8;
ulong RED_TEAM_LEVEL_PTR = 0x103DF80E8;

Team scores .. might just be from the UI itself, but something is writing to it :-)

**Comment by zorgiepoo** [comment]
Afraid I don't have the game on me.

If you're feeling adventurous and have lldb installed, try adding a watchpoint with it to see if it's an issue with Bit Slicer, by doing something like:

```
lldb
process attach --pid <pid_number_of_process>
watchpoint set expression -x 1 -- 0x103DF80D8
cont
```

**Comment by theforcedk** [comment]
Good idea, but you can't attach to the process with lldb :x

Dagobah:~ sudo lldb
(lldb) process attach --pid 2750
error: attach failed: lost connection

Works fine with other processes but the main one:

(lldb) process attach --pid 2755
Process 2755 stopped
Executable module set to "/Volumes/Random/Games/Heroes of the Storm/Versions/Base34190/Heroes.app/Contents/Helpers/GLShaderCompiler".

If I set a break point in Bit Slicer's debugger; it doesn't get called - they must be blocking it. I can't attach with Hopper either, as you cannot run the process by itself, it has to be launched through the bnet client or a switcher (HeroesSwitcher).

http://cl.ly/image/280C0C2t2G3i/Screen%20Shot%202015-03-13%20at%2023.35.27.png

I'll keep trying :-) - love your app.

**Comment by zorgiepoo** [comment]
There shouldn't be a need to run lldb as root using sudo. Other than that, not sure why attaching fails - odd.. Both lldb and hopper (which just uses lldb or gdb) should be able to attach to an already running process.

The screenshot you are showing in Bit Slicer are not actual instructions, so setting instruction breakpoints via the debugger window there doesn't make sense.

**Comment by theforcedk** [comment]
Yeah. The game is probably detecting the attach and rejecting it - I can attach fine (the root thing was just a permission test) to eg. Calculator.app or whatever. They brew up some black wizardry in regards to OpenGL functions too - using some kind of custom wrapper. You're right in regards to the breakpoint, my learning curve is slow but the intuitiveness of your application helps a lot :)

**Comment by zorgiepoo** [comment]
Just for some info, Bit Slicer doesn't actually 'attach' to a process until the it sets its first breakpoint/watchpoint. Debuggers like LLDB and GDB on the other hand use ptrace and are detectable via looking at [that flag](https://developer.apple.com/library/mac/qa/qa1361/_index.html). Custom wrappers around GL code is pretty common for x-platform games. Glad the application is helping out somewhat =P.

**Comment by theforcedk** [comment]
It crashed when I attached with gdb. Hopper can't attach to running process without an external debugger I think, too complicated - I'll try and see what happens in Bit Slicer sometime.

As a thank you, I'll translate your app to Danish :-)

**Comment by theforcedk** [comment]
Also, there's a duplicate comment in [Code] Debugger Registers.strings:

/* Undo action name for changing a register type */
"undoRegisterTypeChange" = "Ændre Register Type";

/* Undo action name for changing a register type */
"undoRegisterValueChange" = "Ændre Register Værdi";

Your comment is the same.. variable is not. I'll correct it in mine.

Second should be: /* Undo action name for changing a register value */

**Comment by zorgiepoo** [comment]
GDB isn't too supported these days on OS X so that doesn't sound too surprising. Hopper has a button to "Attach to process" but I'm not actually remembering how to get it to work myself right now \=. Anyway Hopper just uses LLDB so it's unlikely to help.

Thanks for giving a go at translating the app! I'm actually trying to integrate some Russian translations a someone sent me, so this is all the more awesome =). If you've more notes/questions/issues about translating, create a separate issue though. I'll fix that comment with the others languages. Thanks!

**Comment by zorgiepoo** [comment]
So a friend of mine who had the game was able to indicate why LDLB can't attach to the process, because it makes one or more calls like ptrace(PT_DENY_ATTACH, ...) which will affect LLDB/GBD for attaching.

**Comment by theforcedk** [comment]
Yup, just got the same result - ran it with dtruss. I tried on Windows using Cheat Engine; the addresses i pasted earlier yields no results in regards to callers. Weird.

**Comment by zorgiepoo** [comment]
You can try having LLDB wait for the process and attach when it launches:

```
lldb
process attach --name <name_of_game> --waitfor
```

If this attaches before ptrace is called, this might work. Then you'll have to NOP out calls to ptrace and possibly have it return without error if the game is checking that.

**Comment by theforcedk** [comment]
Sure, that's a good idea. I'm building https://github.com/gdbinit/onyx-the-black-cat in a sec; this should patch PT_DENY_ATTACH.

```c
int 
onyx_ptrace(struct proc *p, struct ptrace_args *uap, int *retval)
{
    /* retrieve pid using exported functions so we don't need definition of struct proc */
    pid_t pid = proc_pid(p);
	char processname[MAXCOMLEN+1] = {0};
    // verify if it's a PT_DENY_ATTACH request and fix for all processes that call it
    if (uap->req == PT_DENY_ATTACH)
    {
        proc_name(pid, processname, sizeof(processname));
        LOG_INFO("Blocked PT_DENY_ATTACH/P_LNOATTACH in PID %d (%s)", pid, processname);
        return 0;
    }
    // for the extra tricky ones : simulate exact behavior
    else if (uap->req == PT_ATTACH && uap->pid == pid)
    {
        proc_signal(pid, SIGSEGV);
        return 22;
    }
    // else it's business as usual, we are not interested in messing with other requests
    else
    {
        return real_ptrace(p, uap, retval);
    }
}
```

**Comment by theforcedk** [comment]
Oh, that might've worked - what you wrote.

Dagobah:~/Projects lldb
(lldb) process attach --name Heroes --waitfor
Process 7665 stopped
Executable module set to "/Volumes/Random/Games/Heroes of the Storm/Versions/Base34190/Heroes.app/Contents/MacOS/Heroes".
Architecture set to: x86_64-apple-macosx.
(lldb) watchpoint set expression -x 1 -- 0x103DF80D8
Watchpoint created: Watchpoint 1: addr = 0x103df80d8 size = 1 state = enabled type = w
    new value: 0
(lldb) cont
Process 7665 resuming
Process 7665 stopped
* thread #1: tid = 0x60ef0, 0x0000000100f7e92d Heroes`___lldb_unnamed_function60404$$Heroes + 333, queue = 'com.apple.main-thread', stop reason = watchpoint 1
    frame #0: 0x0000000100f7e92d Heroes`___lldb_unnamed_function60404$$Heroes + 333
Heroes`___lldb_unnamed_function60404$$Heroes + 333:
-> 0x100f7e92d:  shlq   $0x7, %rsi
   0x100f7e931:  movq   $-0x1, 0x78(%rsi,%rax)
   0x100f7e93a:  movq   $-0x1, 0x70(%rsi,%rax)
   0x100f7e943:  movq   $-0x1, 0x68(%rsi,%rax)

Watchpoint 1 hit:
old value: 0
new value: 0

**Comment by theforcedk** [comment]
Ok, no.. game crashing after continue.

(lldb) process attach --name Heroes --waitfor
Process 7688 stopped
Executable module set to "/Volumes/Random/Games/Heroes of the Storm/Versions/Base34190/Heroes.app/Contents/MacOS/Heroes".
Architecture set to: x86_64-apple-macosx.
(lldb) cont
Process 7688 resuming
Process 7688 exited with status = 1 (0x00000001) 

Seems that onyx-the-black-cat is not the way to go, you need to patch /usr/libexec/kextd .. no.

**Comment by zorgiepoo** [comment]
Did you NOP out ptrace or override it and ret 0 after it attached in lldb and before continuing? Not clear from what output above.

Well it looks like lldb caught the watchpoint so you have some instruction address to look at, at least. Do you think this is a fault in Bit Slicer not catching it, or was it only hit here early on in the process.

**Comment by theforcedk** [comment]
(lldb) process attach --name Heroes --waitfor
Process 9392 stopped
Executable module set to "/Volumes/Random/Games/Heroes of the Storm/Versions/Base34190/Heroes.app/Contents/MacOS/Heroes".
Architecture set to: x86_64-apple-macosx.
(lldb) b ptrace
Breakpoint 1: where = libsystem_kernel.dylib`__ptrace, address = 0x00007fff84a8c2c4
(lldb) b _Exit
Breakpoint 2: where = libsystem_c.dylib`_Exit, address = 0x00007fff9032256a
(lldb) b command add 1
Breakpoint 3: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) br command add 1
Enter your debugger command(s).  Type 'DONE' to end.
> thread return 
> c 
> DONE
(lldb) cont
Process 9392 resuming
Process 9392 stopped
* thread #7: tid = 0x67b0e, 0x00007fff9032256a libsystem_c.dylib`_Exit, name = 'Exception Handler', stop reason = breakpoint 2.1
    frame #0: 0x00007fff9032256a libsystem_c.dylib`_Exit
libsystem_c.dylib`_Exit:
-> 0x7fff9032256a:  pushq  %rbp
   0x7fff9032256b:  movq   %rsp, %rbp
   0x7fff9032256e:  callq  0x7fff9034846a            ; symbol stub for: _exit

libsystem_c.dylib`abs:
   0x7fff90322573:  pushq  %rbp

**Comment by theforcedk** [comment]
I added the breakpoint for _Exit in order to see why it was exiting (it exits with 1 after the pthread breakpoint).. not really much information on that one.

**Comment by theforcedk** [comment]
Yeah, so.. I just found out that the binary is packed also. I give up, is getting too advanced :). Try my luck with some packet sniffing; I did that for Hearthstone (easy tho, not encrypted.. protocol buffers): http://theforce.dk/hearthstone/

Thanks a lot for all your help sir!

**Comment by zorgiepoo** [comment]
You could also just try using a read & write watchpoint to the address in Bit Slicer (or maybe better yet to a pointer to the address if you can find one), looking around at any area of instructions that might be useful to look at. Either way, good luck.
