### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by theforcedk** [zorgiepoo/Bit-Slicer#11]
Very inventive topic name.

Here are the dupes in comments. No duplicate variable names. Behold the power of PHP (sigh).

    (vim) Dagobah:~ php a.php 
    key = /* Undo action name for changing a register type */ for file [Code] Debugger Registers.strings > 1
    key = /* Labels 'Back' menu item in View menu when using debugger or memory viewer */ for file [Code] Memory Navigation.strings > 1

-
```php
<?php
$files = glob('/Applications/Bit\ Slicer\ \(Localized\).app/Contents/Resources/da.lproj/*.strings');
$files = array_map('trim', $files);

foreach ($files as $file)
{
    $buffer = array();
    $lines = file($file);
    $lines = array_map('trim', $lines);

    foreach ($lines as $line)
    {   
        if (empty($line)) continue;

        if ('/' == $line[0] && (strlen($line) > 2 /* no copyright */))
            @$buffer[$line] += 1; // throws notice, we don't care
    }   

    foreach ($buffer as $key => $val)
    {   
        if ($val > 1)
            printf("key = %s for file %s > 1\n", $key, basename($file));
    }   

    $buffer = array();
}
```

**Comment by zorgiepoo** [comment]
I pushed all the Russian localization changes if you want another reference to look at. (Fortunately pluralization rules in Danish look as simple as in English).

Appreciate writing the script to find the duplicates =P.
