### ISSUE TITLE
Feature request: Follow pointer in Memory Viewer

### ISSUE THREAD

**Issue by theforcedk** [zorgiepoo/Bit-Slicer#12]
Hei

A feature I'm missing is the ability to add a pointer to the Memory Viewer, as you can add int and floats. You need to be able to define what to read at the address the pointer resolves to.

Right now, I manually select 8 bytes from the Memory Viewer, add a new pointer to Bit Slicer, add a new variable (eg. 8 bit string) with the pointer's address in []'s and that shows me the value.

This would be awesome to have in the Memory Viewer itself; quickly be able to read what's at the other end.

**Comment by zorgiepoo** [comment]
Sounds like a good idea in the future.

You can simplify your current workflow if you just add a 8-bit string, and alter its address in []'s.

**Comment by zorgiepoo** [comment]
But this convenience doesn't help much if the pointer is not direct to what you want, so it may not be that much worth adding. Possibly an easier way to jump to a pointer in the memory viewer would be better.

**Comment by theforcedk** [comment]
You might be right; or a quick way to add the selected address (+offset) in Memory Viewer as a pointer to the Bit Slicer window (with read type eg string/int/float) - this is what I use for trial and error'ing because my assembly skills are seriously lacking, so I browse around memory hoping to get a break ^_^

Thanks for considering
