### ISSUE TITLE
Source of FindPointerTest

### ISSUE THREAD

**Issue by theforcedk** [zorgiepoo/Bit-Slicer#13]
Hey

Can you provide the source for http://dl.dropbox.com/u/10108199/FindPointerTest.zip? I'm interested in modifying it a bit and watching what happens with Bit Slicer.

Ps., done translating soon

Thanks

**Comment by zorgiepoo** [comment]
Sure, although I don't think it is that interesting. http://zgcoder.net/zfw/FindPointerTestSrc.zip

**Comment by zorgiepoo** [comment]
Off topic, but did you get a chance to finalize the Danish translations? Would love to take a look at them.
