### ISSUE TITLE
Cheat Engine Collaboration?

### ISSUE THREAD

**Issue by ylluminate** [zorgiepoo/Bit-Slicer#14]
I wonder if it is worth collaborating with Cheat Engine since it is effectively not going to be actively developed from what the developer last said here well over a year ago: http://forum.cheatengine.org/viewtopic.php?p=5592901#5592901

It would seem quite useful to be able to leverage some of the community efforts that exist for Cheat Engine in Bit Slicer.

**Comment by zorgiepoo** [comment]
If the developer wants to exchange info with me or vise versa, that's fine. Well, Bit Slicer is also open source with lots of info open about, anyway. I assume the same might be true about CE's mac port but I'm not sure.

I also used to collaborate a bit with The Cheat's developer back in the day.. I believe I've also made a comment on that thread you linked giving some advice on something a while back.

Keep in mind I actually develop on a Mac, and Bit Slicer is designed using native APIs, and thus behaves like a proper application. In some ways, these projects are different, and some things people suggest like being able to open CE files really makes no sense from my standpoint.

Aside, this is not really an issue report and nothing is really being suggested other than "collaboration should happen" so I'll have this be closed.
