### ISSUE TITLE
Search in between

### ISSUE THREAD

**Issue by terrybleger** [zorgiepoo/Bit-Slicer#19]
Please add feature for searching value in between (combined greater than & less than).

Will need two search inputs.
Input 1(greater than or equal) >= x =< Input 2 (less than or equal).

Thanks.

**Comment by etybyte** [comment]
This feature already exists. If you use the Greater than or less than search there is a box on the bar below the search that allows you to specify the other side (below for greater than and above for less than).

**Comment by terrybleger** [comment]
Unfortunately it is not working that well. I've tried hundred of times without success. I hate to reboot to Windows just to play games with Cheat Engine. With CE for example, if the value is 3.5, I can just search for >= 3 and <= 4, and I will get the value within 2 or 3 searches. But with BS, the result will just be inconsistent, I search for >= 3, then search for <= 4, it's 2 steps, if result is consistent then it would be great, but I've to keep search until 20th times, but still never get the value because the result is weird. Because the result is too many, maybe until I tried for 2000th times I'll get the result. But I prefer just reboot to windows and use CE instead.

**Comment by zorgiepoo** [comment]
Please see issue #6 which this issue is a duplicate of. In short, doing a between search, although not super obvious, is more possible than you may think. What you're missing is that there is the search field *and* another bounded field, allowing you to do a search like > 3, < 4 in one step.

**Comment by terrybleger** [comment]
OK thanks. I didn't notice it before.
