### ISSUE TITLE
Searching unknown value type

### ISSUE THREAD

**Issue by terrybleger** [zorgiepoo/Bit-Slicer#20]
Is it possible to have feature like Cheat Engine/GameHack that can search for unknown value type and then search for changes (is bigger than unknown & is less than unknown)?

**Comment by etybyte** [comment]
You can accomplish this by starting your search with "store all values" (cmd-g or the "bucket icon next to the search bar). Then you can search for less than stored value or greater than stored value to look for changing variables.

**Comment by zorgiepoo** [comment]
See [the wiki page](https://github.com/zorgiepoo/Bit-Slicer/wiki/Storing-All-Values) for more information.

**Comment by terrybleger** [comment]
OK thanks
