### ISSUE TITLE
Reduce window clutter.

### ISSUE THREAD

**Issue by chexo3** [zorgiepoo/Bit-Slicer#21]
I'm using Bit Slicer 1.6.2, as I can't run the new versions, but I've seen the new versions and this a problem there too.
You end up getting very cluttered, is it possible we could get a smaller interface to choose between searches, so you can find variables, assign some sort of label seperate from the "name" value added by bit slicer, and maybe even have a target value, when the value, say your health, is changed, by getting damaged, you'll have a different value. Whenever the cheat is clicked on in the searches menu, the value is changed to the target. This can be timed as well, and maybe even scripted in the future, if that is added.

**Comment by zorgiepoo** [comment]
First, 1.6 is vastly more cluttered than 1.7 in my opinion. I have dropped support for 1.6, so any discussion here has to be related to the latest version. And I also do not have a very good idea anymore of how that version works in some aspects.

The name column was changed to description column, which became friendlier/larger and is what is intended for labels and annotations. Paragraphs can even be put into these descriptions. Altering them works with a text area such as the one I'm typing in right now.

It sounds like "target value" to me that may be related to [frozen variables](https://github.com/zorgiepoo/Bit-Slicer/wiki/Search-Windows), or [writing a script](https://github.com/zorgiepoo/Bit-Slicer/wiki/Introduction-to-Scripting) (1.7 only). If this is still a problem and has nothing to do with window clutter, it should be reported in a separate issue.

**Comment by chexo3** [comment]
Ok. Is it possible that 1.7 could be made to support older versions? I don't know much about the code but if there isn't much specific to newer versions it should be possible.

**Comment by chexo3** [comment]
Hey, perhaps you can point me to apple's development guides, and info on how memory editors work for mac using kernal functions.

**Comment by zorgiepoo** [comment]
I described some possible dependencies in #9. You can find many of the functions being called in Bit Slicer's source code - see ZGVirtualMemory.h/c. Feel free to google the kernel functions that are being called, but there's not that much documentation on them.

In general, I'd like to support the latest major OS, plus one major version behind that. Supporting anything beyond that depends on convenience.
