### ISSUE TITLE
question about binary release

### ISSUE THREAD

**Issue by r4ccoon** [zorgiepoo/Bit-Slicer#22]
Hi, 
Thanks for this awesome program, but a quick question, 
I wonder why you do not have the binary release?
I have managed to compile it myself, but for average user, seems it is going to be a bit difficult for them.

Thank you, cheers.

**Comment by Tyilo** [comment]
They are on bitbucket: https://bitbucket.org/zorgiepoo/bit-slicer/downloads

But why don't you also release the binaries using GitHub's release system?

**Comment by zorgiepoo** [comment]
The stable release is the very first thing linked on this repos README file. See https://github.com/zorgiepoo/Bit-Slicer . BitBucket is just one mirror I've them hosted. Most of the downloads probably are from MacUpdate which link to the binaries from my own website.

I probably should use GitHub's system. GitHub didn't always have a release system, that's probably the only reason why I haven't used it.

**Comment by zorgiepoo** [comment]
GitHub's release system is now being used.
