### ISSUE TITLE
How to use floats/doubles?

### ISSUE THREAD

**Issue by chexo3** [zorgiepoo/Bit-Slicer#23]
I was looking at the float menu, trying to search for a floating point value, but the epsilon and value box is confusing, why are there two inputs?

**Comment by zorgiepoo** [comment]
Representing numbers as floating points and doing calculations on them may not lead to 100% accuracy. So, "Epsilon" (renamed to Round Error in recent versions) is a +- threshold. For example, if you search for values that equal 20.0 with an epsilon of 0.1, you will get values between 20.0 - 0.1 and 20.0 + 0.1 inclusive.

To put it more mathematically, it adjusts the definition of equals on floating points such that the following condition is met: abs(x - target) <= epsilon
