### ISSUE TITLE
No longer asking for permissions

### ISSUE THREAD

**Issue by mr0everywhere** [zorgiepoo/Bit-Slicer#31]
I have the most recent build 1.7.6 (1123) of bitslicer, and os x 10.11.3 (15D21) and bit slicer no longer asks for permission to start and will not read memory anymore. i do not know of any updates to either since the last time it worked but it will not work anymore for any program.

**Comment by zorgiepoo** [comment]
Very odd. Few things I can think of:

1. Try opening the Console application (located in /Applications/Utilities/ or use Launchpad or Spotlight to search for it). Filter for Bit Slicer. If any relevant logs show up, please copy and paste them here so I can take a look.

2. Bit Slicer should ask for a password prompt once per restart. You can always try rebooting your Mac to see if that fixes anything.

3. Bit Slicer no longer can access System/Apple's applications on 10.11 due to a protection they put in place. Since these applications should be filtered out, I doubt this is the issue though.

**Comment by servel333** [comment]
kernel[0]: Sandbox: Bit Slicer(8237) System Policy: deny(1) mach-priv-task-port 64985

This seems to happen for me only when I try to access Chrome memory.

**Comment by zorgiepoo** [comment]
Yeah, on OS X 10.11, Chrome blocks memory access as explained in #32 in almost the same manner as Apple's applications block it.

**Comment by Ghirigoro** [comment]
I'm also running into this issue where searching does nothing (not trying with Chrome - trying this on Steam games and it happens for all of them). I'm running this on 10.12.6 on a Macbook Pro with touchbar. Tried recompiling from source but that didn't make any difference. Here's what the console shows when booting up Bit Slicer. Trying a search doesn't cause any messages to be logged (at least not Bit Slicer ones)

```default	20:24:13.800816 -0400	Bit Slicer	[0x7fe1538e0a00] Created session
default	20:24:13.801158 -0400	Bit Slicer	[0x7fe1538e0a00] Decoding: C0 0x00130013 0x0003354A 0x11111100 0x00000000 1121
default	20:24:13.801184 -0400	Bit Slicer	[0x7fe1538e0a00] Options: 19x19 [FFFFFFFF,FFFFFFFF] 0001D060
default	20:24:13.801256 -0400	Bit Slicer	[0x7fe1538e0a00] Decoding completed without errors
default	20:24:13.801443 -0400	Bit Slicer	[0x7fe1538e0a00] Releasing session
default	20:25:06.520035 -0400	Bit Slicer	Claim 34591AF2-AB4A-4F70-874F-5485C7E87125 granted in client
default	20:25:06.520082 -0400	Bit Slicer	Claim 34591AF2-AB4A-4F70-874F-5485C7E87125 invoked in client```

**Comment by zorgiepoo** [comment]
Steam games work for me on 10.12.6, or at least Super Hexagon does. Does searching work in any game or application at all, even those outside of Steam? Maybe the games you are trying in particular just don't work?

I'm not really familiar with those logs, but I'd suggest having Console open before launching Bit Slicer to have all relevant logs available. I'd also suggest the rebooting the computer to see if that changes anything.

**Comment by Ghirigoro** [comment]
I haven't had any success with any games on Steam (can't remember all the titles but at least 4 or 5 of them including Everspace and Dead Cells) but I've also tried Airmail and Photoshop with no success.

I've also tried rebooting the machine multiple times with no success. Are there particular security settings that should be used? (I have "allow app store and identified developers" selected which is as permissive as Sierra allows me)

Here are the logs from a reboot and restart of Bit Slicer (i.e. I had the console running before starting the app)

```
default	17:04:24.130040 -0400	kernel	[Bit Slicer pid:844 mux-aware] starting, non-mux-aware app count 2, switch-state 0 IG FBs 0 EG FBs 3:1f power-state 0 3D busy HDA busy
default	17:04:24.260127 -0400	Bit Slicer	[0x7ffd290d9c00] Created session
default	17:04:24.260451 -0400	Bit Slicer	[0x7ffd290d9c00] Decoding: C0 0x00130013 0x0003354A 0x11111100 0x00000000 1121
default	17:04:24.260475 -0400	Bit Slicer	[0x7ffd290d9c00] Options: 19x19 [FFFFFFFF,FFFFFFFF] 0001D060
default	17:04:24.260545 -0400	Bit Slicer	[0x7ffd290d9c00] Decoding completed without errors
default	17:04:24.260716 -0400	Bit Slicer	[0x7ffd290d9c00] Releasing session
```

**Comment by Ghirigoro** [comment]
Just tried downloading the app (rather than building it from source) and it works. Not sure what I did wrong (maybe some issue around different versions of XCode). Sorry for the bother. I'll try stepping through the source version with a debugger and will let you know if I come up with anything.

**Comment by zorgiepoo** [comment]
See building section from https://github.com/zorgiepoo/Bit-Slicer/wiki/Source-Code

If the signing certificate isn't set up properly, searching won't work.
