### ISSUE TITLE
Freeze does not work

### ISSUE THREAD

**Issue by joobei** [zorgiepoo/Bit-Slicer#33]
I'm not exactly how Freezing a value is supposed to work. If it's supposed to monitor a value and if it gets changed, it quickly changes it back to its original value then it doesn't work I think. Although I've "frozen" a player's health when he gets shot the program changes the frozen value.

**Comment by zorgiepoo** [comment]
Freezing just works by overwriting a value at a memory address every small interval. It doesn't monitor the value and it doesn't prevent the game from changing the value.

Another approach is watching for write accesses (this is monitoring) to find what instructions (code) is accessing the variable. Then you could proceed to NOP (no-operation) the instructions that are found, to prevent them from being executed.

**Comment by joobei** [comment]
Fantastic. Thank you very much!
