### ISSUE TITLE
How to declare base address

### ISSUE THREAD

**Issue by joobei** [zorgiepoo/Bit-Slicer#34]
I'm curious how I can set addresses relevant to some base address. i.e. I find two values whose addresses are 8 bytes apart from each other. Every time the program starts I have to search for the "base" address, but as soon as I've found it then I want the remaining values in the set to be immediately mapped relevant to that one. Is that possible?

**Comment by zorgiepoo** [comment]
Bit Slicer has syntax for referencing pointers / base addresses when altering a variable's memory address. May want to take a look at [this page](https://github.com/zorgiepoo/Bit-Slicer/wiki/Pointers).

**Comment by joobei** [comment]
Thanks for the info :)

**Comment by joobei** [comment]
Hello. I really appreciate your help and that page was super helpful. It's funny how whenever I search for a variable in my games I always get two values. This was the case with your app as well. If I search for a pointer for the first value I don't get anything, but the second value returns a pointer when I search for it. Could you please explain what the difference is between the two values?  Just out of curiosity. I'll update the wiki afterwards.

![pointer](https://cloud.githubusercontent.com/assets/2638631/14100504/46256eb0-f58e-11e5-84c7-3ee1a14c6ff7.png)

**Comment by zorgiepoo** [comment]
One is probably a false positive. Sometimes you can try adjusting the value that is false positive, let the program you're targeting change the value, and it may get "out of sync" with the value you actually desire.
