### ISSUE TITLE
No longer working in Chrome

### ISSUE THREAD

**Issue by fleep** [zorgiepoo/Bit-Slicer#35]
Running Chrome 50.0.2661.94 64-bit on OSX El Capitan version 10.11.3. 

I am trying to slice "Cave Heroes" running in Flash. No matter which Chrome process I select, every search completes almost instantly with no result. I used to be able to do this with no problem as recently as 3 months ago.  I have used Chrome Task Manager to find the correct processes for the tab I'm running AND for the Flash plugin - but from the app's response time, it doesn't look as though a search is happening at all.

A search for the 32 bit int "1" should almost always return a result in any app. But this search returns nothing.

**Comment by fleep** [comment]
Likely a dupe of https://github.com/zorgiepoo/Bit-Slicer/issues/32

**Comment by Qix-** [comment]
Definitely a dupe. It will not work in chrome anymore.

**Comment by zorgiepoo** [comment]
I created an automator script mentioned in #32 that may help.
