### ISSUE TITLE
Cannot read VirtualBox's memory

### ISSUE THREAD

**Issue by mvasilkov** [zorgiepoo/Bit-Slicer#38]
HI all,

I'm running OS X 10.10.5, so this isn't a duplicate of #32. However, the symptoms are very similar: cannot search or view the memory of VirtualBox's process (VBoxHeadless).

Can anyone maybe suggest a workaround?

**Comment by zorgiepoo** [comment]
I reproduced that behavior here. I think the euid of that program is root and it has setuid bit set or something. You can attach with lldb if you run lldb as root, for example. Unfortunately Bit Slicer does not have a command line version so it's not "safe" or "supported" to run Bit Slicer as root, although Bit Slicer used to normally run like that a long time ago.

In https://github.com/zorgiepoo/Bit-Slicer/commit/f1fc6e6ece1f3ce5f2138995530b14299abd66ae, I allowed all processes to be shown in the target list if Bit Slicer is run as root, so you can feel free to try a build [here](https://zgcoder.net/zfw/bit-slicer-root-filter.zip) if you want. Just keep in mind you have to run the app as root which is a huge security hole & not tested thoroughly, but if it works for you..!

**Comment by mvasilkov** [comment]
Wow, thanks a lot! Works like a charm on an Android game running inside a VM.

**Comment by smileytechguy** [comment]
Awesome!  Running as root solved my issues, even after I tried your resigner.  I found the exact path with `ps aux | grep MacOS" and just ran the direct command with sudo.
