### ISSUE TITLE
Debug prompt dissapears

### ISSUE THREAD

**Issue by wesselvdv** [zorgiepoo/Bit-Slicer#42]
Having a script with an execute function active, and activating a second one without an execute function but with a debug.prompt in the init, causes the debug.prompt to malfunction. 

Having an execute function in the second script variable that has the debug.prompt fixes the issue.

So it's mostly weird behaviour. Took me a while to figure out.

**Comment by zorgiepoo** [comment]
Thanks, this should be fixed now in the code and be in the next build. The bug occurs when some scripts have execute function defined and other scripts don't have execute function defined.
