### ISSUE TITLE
ARC semantic issue

### ISSUE THREAD

**Issue by Arcrammer** [zorgiepoo/Bit-Slicer#49]
When I tried to compile the `.xcodeproj` (Version 9.1 (9B55) — High Sierra 10.13.2 (17C205)) I'm getting the following build error:

```
/Users/alexander/Desktop/Bit-Slicer/Bit Slicer/ZGMemoryWindowController.m:561:6: Multiple methods named 'processID' found with mismatched result, parameter type or attributes
```

To me it seems like `ZGProcess.processID` is conflicting with Core Data?

**Comment by Arcrammer** [comment]
Nevermind this — Didn't realize I can just download the app!

**Comment by zorgiepoo** [comment]
Yeah, compiling is a little more involved. I committed a fix for this one line though.
