### ISSUE TITLE
Unable to sort result set columns

### ISSUE THREAD

**Issue by Arcrammer** [zorgiepoo/Bit-Slicer#50]
When I search for a very specific value I might want to change all occurrences of that value, but I've noticed a lot of the time there will be random results where the value doesn't appear. I can post an example if that helps, but basically I'm just asking for sorting by the column or a find and replace. Also, not sure why I'm getting results that don't match my search query. (I'm at work right now so I'll need to take some time to post a screenie)

This is an issue that happens when I search by Byte Array but it doesn't seem to happen for other data types. Come to think of it this might be an issue with my particular game where the value is what I search for when Bit Slicer gets the results but then it changes after the results populate. I'm not sure.

Is sorting by the column something we could potentially have in Bit Slicer?

**Comment by zorgiepoo** [comment]
What happens when you do subsequent narrow searches using the same search value; are you able to narrow down the variables to ones that don't change often? Sorting isn't really provided due to how values (and sometimes addresses) can change at any point and how the table can display different types. Sounds like you want sorting to work around some other problem though.

**Comment by Arcrammer** [comment]
Narrowing it down by searching again did actually remove the unexpected results. I'll have to remember to do that the next time I see unexpected results! Thank you for explaining and helping me figure this out.

**Comment by zorgiepoo** [comment]
Typically you want to change the value in game so you can narrow down the search with a different value, to reduce the number of results. Or search for a very unique value. It’s ideal to get a very low number of results back (optimally 1). It’s not safe to alter dozens of random variables.
