### ISSUE TITLE
Small Hotkey documentation issues

### ISSUE THREAD

**Issue by pascalwerz** [zorgiepoo/Bit-Slicer#51]
1 - In [Debug register hotkeys documentation](https://github.com/zorgiepoo/Bit-Slicer/wiki/Debug-register-hotkeys), function
**isRegisteredHotkey**
is documented with a different spelling:
**isHotkeyRegistered**

2 - On same page, example section makes use of **keymod.FUNCTION** which is not listed as a key modifiers constant. It doesn't seem to refer to the 'Fn' key required to access F1-F12 on 100+ keys keyboards.

**Comment by zorgiepoo** [comment]
Thanks, fixed the documentation issues. Not actually sure myself if `keymod.FUNCTION` is required or not but including it anyway.
