### ISSUE TITLE
Kernel panic: vm_page_insert_internal inserted at offset past object bounds

### ISSUE THREAD

**Issue by aisoard** [zorgiepoo/Bit-Slicer#53]
I get a reproducible Kernel Panic when using Bit Slicer on some games (for some others it works flawlessly).

> panic(cpu 0 caller 0xffffff800bb0c725): "vm_page_insert_internal: (page=0xffffff80164be968,obj=0xffffff80446b1300,off=0xfffffffffffff000,size=0x0) inserted at offset past object bounds"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4570.41.2/osfmk/vm/vm_resident.c:1490
> 
> BSD process name corresponding to current thread: Bit Slicer
> 
> Mac OS version: 17D102
> 
> Kernel version:
> Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
> Kernel UUID: 18D901F1-4A03-3FF1-AE34-C26B2732F13C
> Kernel slide:     0x000000000b600000
> Kernel text base: 0xffffff800b800000
> __HIB  text base: 0xffffff800b700000
> System model name: MacBookPro11,3

I am not sure how to investigate the issue to find a work-around.

**Comment by zorgiepoo** [comment]
Hm. If you've more details / reproducible steps / examples of games, best to continue discussion through email (zorgiepoo@gmail.com) and I can answer your other questions too. IRC doesn't work well if a user disconnects from the room.

**Comment by aisoard** [comment]
Sure, I sent you an e-mail with additional information but there isn't much as kernel panic are brutal.

The bug is triggered as soon as I hit "search" in Bit Slicer (half a second later the screen goes dark).

**Comment by zorgiepoo** [comment]
I wasn't able to repro, not really actionable for me. Configuration could have changed since.
