### ISSUE TITLE
Crashes after 15 seconds

### ISSUE THREAD

**Issue by Genocide789** [zorgiepoo/Bit-Slicer#56]
When I use bitslicer to slice a game like headsoccer it used to work fine. I hadn't used it in a while as I hadn't needed it. When ii reset my mac I went to slice the games again, bitslicer opened, and then after 15 seconds it force closed. I tried to fix it but I don't know what to do. People are saying it's because some apps don't work on my mac version which is mac OS High Sierra, but I don't think thats true. Could somebody please help me with this as I can't find anybody with the same problem and I feel like I am the only person with this problem.

**Comment by zigmasdirigeant** [comment]
Hello Genocide789,
We need more information about the problem. **Perhaps the error report from the crash?** That would really help us backtrack where’s the problem.

Also, is the problem totally timed? As, it always crash after 15 seconds after opening Bitslicer, or after you do something?

There are many thing that could be happening here.

Cheers!

**Comment by zorgiepoo** [comment]
In addition to the above, is Bit Slicer crashing or head soccer crashing? And is this after you do an alteration?

**Comment by Genocide789** [comment]
I don't get any error report after bitslicer crashes. It closes as if I myself quit it. Even when I don't do anything on bitslicer it closes, so I don't have enough time to slice data.. It isn't always the same time as it varies from 8 to 15 seconds.

**Comment by zigmasdirigeant** [comment]
@Genocide789 ,
We don’t have enough information to troubleshoot your problem.
Could you send us the link to the game? Full name or url.
Also, have you tried reinstalling Bitslicer latest version? 
Delete the app in your applications folder, and download the latest version from here:  [BITSLICER](https://zgcoder.net/software/bitslicer/dist/stable/Bit%20Slicer.dmg)
Run the app, remember to give it admin access by giving the admin password when asked for it, attach your game to bit slicer and try again. 
Tell us how did it go.
