### ISSUE TITLE
[Request] Add Alignment Option

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [zorgiepoo/Bit-Slicer#57]
in Cheat Engine their is a an alignment function which allows to narrow down memory searches even further such as 4 byte alignment will cause to search for addresses dividable by 8 only).

more and more games are getting more complex and encrypted. I'm trying to keep up with latest methods but I'd prefer if Bitslicer becomes the better Alternative of cheat engine for Mac support most critical features.

**Comment by zorgiepoo** [comment]
An option is available to turn alignment off (to 1 for all data types) in the gear button at the bottom left corner of a search window.
