### ISSUE TITLE
I made a Discord server for BitSlicer

### ISSUE THREAD

**Issue by AlePur** [zorgiepoo/Bit-Slicer#58]
Link: [invitation code]
(Python experts, Zorgiepoo and BitSlicer experts can get special roles)
Zorgiepoo, if you don't like that I made it or that I'm using the Bitslicer icon, tell me and I will take it down.

**Comment by erfg12** [comment]
Is there a Discord server made?

**Comment by zorgiepoo** [comment]
I added a [discord link](https://discordapp.com/invite/9jWe8Mf) to the read me page with valid invite link that I manage now, I guess..
