### ISSUE TITLE
pointer_scanner branch

### ISSUE THREAD

**Issue by sandiz** [zorgiepoo/Bit-Slicer#59]
Hi zorgiepoo,

great work on the tool! any plans on getting the `pointer_scanner` branch merged ? 

cheat-engine has a feature where given a target pointer it will find a pointer chain from a static address to the given address. this branch seems to be doing something like that..

i updated the branch to [latest](https://github.com/zorgiepoo/Bit-Slicer/compare/pointer_scanner...sandiz:pointer_scanner?expand=1), but it gives a bad access error whenever i try to search for a pointer here:

https://github.com/sandiz/Bit-Slicer/blob/pointer_scanner/Bit%20Slicer/ZGSearchFunctions.mm#L477

appreciate any help in this direction!

**Comment by sandiz** [comment]
```
diff --git a/Bit Slicer/ZGSearchFunctions.mm b/Bit Slicer/ZGSearchFunctions.mm
index 156267fd..935090bb 100644
--- a/Bit Slicer/ZGSearchFunctions.mm
+++ b/Bit Slicer/ZGSearchFunctions.mm
@@ -470,11 +470,16 @@ static NSMutableData *ZGSearchForAllPointerCandidates(ZGMemoryMap processTask, Z
                {
                        ZGMemorySize numberOfVariablesFound = 0;
                        ZGMemoryPointerEntry memoryAddressesEntries[MAX_NUMBER_OF_STACK_ENTRIES];
-
+                       //NSLog(@"dataIndex %llu endLimit %llu ", dataIndex, endLimit);
                        ZGMemorySize numberOfStepsToTake = MIN(MAX_NUMBER_OF_STACK_ENTRIES, (endLimit + dataAlignment - dataIndex) / dataAlignment);
                        for (ZGMemorySize stepIndex = 0; stepIndex < numberOfStepsToTake; stepIndex++)
                        {
-                               ZGMemoryAddress value = *(static_cast<ZGMemoryAddress *>(static_cast<void *>(static_cast<uint8_t *>(bytes) + dataIndex)));
+                               if(dataIndex == endLimit) {
+                                       dataIndex += dataAlignment;
+                                       break;
+                               }
```
got past the error with ^this diff. pointer chains are now successfully printed in the console! (had to turn off address sanitizer in xcode though)


![image](https://user-images.githubusercontent.com/5438703/46712041-e7291e80-cc03-11e8-8ead-3b683638cc96.png)

**Comment by zorgiepoo** [comment]
Hah, yeah that branch is really really incomplete and doesn't do that much if I recall right (no narrowing or UI for sure). I haven't looked at it probably in years now, but it's great to see there's some interest. I'm unlikely to continue working on it though; it's a pretty challenging problem.

While that type of pointer scanning is 'easy', it's also likely often to be more inefficient than finding the addresses and offsets by setting a watchpoint and debugging the code.

**Comment by zorgiepoo** [comment]
Another middle ground I've used in the past is writing a script that hooks in somewhere by setting a breakpoint if finding a static address and offsets is too time consuming.
