### ISSUE TITLE
Google Chrome Memory Cannot Be Searched Due To System Protections (Question)

### ISSUE THREAD

**Issue by x11joe** [zorgiepoo/Bit-Slicer#60]
Like the title implies I got this message for Google Chrome while attempting to test if any of the memory can be modified for a project I'm worki
![screen shot 2018-10-27 at 10 05 19 am](https://user-images.githubusercontent.com/33452445/47607057-2317fe00-d9d0-11e8-883d-100513717770.png)
ng on.  Why is this the case? Is there a way around this?

**Comment by zorgiepoo** [comment]
Because Chrome a couple years ago opted into protections preventing it from being debugged. The question button on that dialog leads [here](https://github.com/zorgiepoo/Bit-Slicer/wiki/Security-Protections).
