### ISSUE TITLE
Allow disabling of search notifications

### ISSUE THREAD

**Issue by Cin316** [zorgiepoo/Bit-Slicer#62]
Every time a search completes, a notification is sent to notification center.  This does not make very much sense to me, as searches complete nearly instantly.  At the very list, there should be a setting in preferences to turn this feature off.

**Comment by zorgiepoo** [comment]
The settings to turn it off are in System Preferences under Notifications. Also, the expected behavior (that I reproduce) is that Bit Slicer doesn't show search notifications if Bit Slicer is the frontmost application.
