### ISSUE TITLE
Specify range of memory for all search operations?

### ISSUE THREAD

**Issue by gingerbeardman** [zorgiepoo/Bit-Slicer#64]
It would be cool if I could specify a range of the app memory that I am interested in.

For example I am only interested in searching the PlayStation memory range when looking for cheats using RetroArch emulator.

Thanks!

**Comment by zorgiepoo** [comment]
At the bottom left of the window there's an advanced options (gear icon) which includes specifying a beginning and/or ending address.

**Comment by gingerbeardman** [comment]
Thanks!
