### ISSUE TITLE
[Feature request] "Unknown intial value" search and "decreased" & "increased" values

### ISSUE THREAD

**Issue by zocoi** [zorgiepoo/Bit-Slicer#65]
Cheatengine has this feature which scans all the memory variables and allows filtering by "increased" or "decreased" value to nail down a couple of potential values. It helps to monitor and trace a certain value based on actions on the game. It's especially helpful for game which obfuscate the variables with unpredictable formula.

**Comment by zorgiepoo** [comment]
yep, it's possible but it works differently.

https://github.com/zorgiepoo/Bit-Slicer/wiki/Storing-All-Values
https://github.com/zorgiepoo/Bit-Slicer/issues/25
https://github.com/zorgiepoo/Bit-Slicer/issues/20
