### ISSUE TITLE
Memory not found due to system protection

### ISSUE THREAD

**Issue by Skavarotti** [zorgiepoo/Bit-Slicer#68]
I can't scan the memory on a Mac OS. When you start scanning, a Bit Slicer window appears with the message: "Search error. The application memory can not be found because of the protection system.". Executed the (defaults write com.zgcoder.BitSlicer ZGRemoveRootlessProcessesKey -bool NO) command in the terminal, it did not help. Apple probably shut down memory access with its latest update. Is there any way around this?

**Comment by zorgiepoo** [comment]
I believe there is a help button on that window that leads to [here](https://github.com/zorgiepoo/Bit-Slicer/wiki/Security-Protections).
