### ISSUE TITLE
Bit Slicer suddenly doesn't work for any app

### ISSUE THREAD

**Issue by stupidfive** [zorgiepoo/Bit-Slicer#73]
Currently on macOS Catalina v10.15.7. Bit Slicer works for me a month ago and I'm pretty sure no OS update had happened on my machine since my last successful attempt of Bit Slicer memory editing.

Today when I opened BitSlicer, no prompt is shown for my password as before. And **all the apps** (including the app I successfully edited a month ago) show

```
Search Failure
[AppName]'s memory cannot be searched due to system protections.
```

when I search for anything in Bit Slicer.

Tried the following approaches but all returned the same outcome:
- Reboot my mac
- Update the latest version
- Delete Bit Slicer and install other releases including alpha releases from GitHub
- Download Bit Slicer source code and run on Xcode

The article on [Security Protections](https://github.com/zorgiepoo/Bit-Slicer/wiki/Security-Protections) doesn't quite describe what I'm experiencing, since it indicates this only happens on some of the apps and it doesn't mention the missing prompt on Bit Slicer startup.

When I run the application in Xcode and execute a search, the follow loggings will show

```
Mach port is not valid for process 460
ZGDocumentWindowController failed to grant access to PID 460
```

Willing to assist further in locating the issue.

**Comment by zorgiepoo** [comment]
`task_for_pid()` on the specific app/game you're targeting is failing here. Because it fails, it won't bring up an authentication prompt if needed (debuggers like Bit Slicer only need to request for successful auth once per system boot).

> [AppName]'s memory cannot be searched due to system protections.
When task_for_pid fails, Bit Slicer invokes `codesign` on the target binary and shows this error when the binary is signed with protections that would prevent Bit Slicer from debugging it. So, this is very unlikely to be wrong and I would have to refer you to the [Security Protections](https://github.com/zorgiepoo/Bit-Slicer/wiki/Security-Protections) article.

The application you're trying to target may have been automatically updated since you've last looked at it or something of that nature. If you try to create a new Cocoa App in Xcode and run it, Bit Slicer can probably successfully target it.

**Comment by stupidfive** [comment]
> `task_for_pid()` on the specific app/game you're targeting is failing here. Because it fails, it may not bring up an authentication prompt if needed (debuggers like Bit Slicer only need to request for successful auth once per system boot).
> 
> > [AppName]'s memory cannot be searched due to system protections.
> 
> When task_for_pid fails, Bit Slicer invokes `codesign -dv` on the target binary and shows this error when the binary is signed with protections (`runtime`, `restrict`) that would prevent Bit Slicer from debugging it. So, this is very unlikely to be wrong and I would have to refer you to the [Security Protections](https://github.com/zorgiepoo/Bit-Slicer/wiki/Security-Protections) article.
> 
> The application you're trying to target may have been automatically updated since you've last looked at it or something of that nature. If you try to create a new Cocoa / macOS App in Xcode and run it, Bit Slicer can probably successfully target it.

I've tested on a dozen of other apps and got the same result. The app I worked on a month ago is a cracked app that is update disabled. So it seems `task_for_pid()` is failing on my machine for all the processes for some reason other than app-wise System Integrity Protection.

I'll do some more testing with `task_for_pid()` and come back to you with more information.

**Comment by zorgiepoo** [comment]
I guess it's also possible you had SIP disabled on your system at one point and it somehow got reverted to be enabled.

If the output from `codesign -dv` on the application in question has `runtime` or `restrict` in the `flags` of the `CodeDirectory` line then it's simply opted into the hardening.

Recalling that lots of apps worked before is not an objective way of testing if an app in question should be debuggable.

**Comment by stupidfive** [comment]
@zorgiepoo True. The apps I've tested yesterday are all popular apps that are hardened. So it's still the SIP issue. Many thanks.

**Comment by stupidfive** [comment]
@zorgiepoo True. The apps I've tested yesterday are all popular apps that are hardened. So it's still the SIP issue. Many thanks.

**Comment by transparentmask** [comment]
well, If you want to fix this local, maybe you can remove code sign of that app with "codesign --remove-signature xxx.app" command, after remove code sign, I can search its memory.

**Comment by zorgiepoo** [comment]
You can try to remove or re-sign the app like that (removing its entitlements preventing debugging). Depending on the app that could potentially stop it from functioning correctly however so it’s not something I can recommend in general.

**Comment by TheRealxMF** [comment]
i have same problem
how to fix
