### ISSUE TITLE
[Feature Request] Can you add a feature that we can see decimal value in memory viewer or debugger.

### ISSUE THREAD

**Issue by FlandreScarle7** [zorgiepoo/Bit-Slicer#74]

**Comment by zorgiepoo** [comment]
If you're talking about floating point, in the memory viewer you can show the data inspector from the menu bar (Memory -> Show Data Inspector) and then change the data type to Floats. If you're in the debugger and the program hit a breakpoint, you can change the data type of any of the registers to show you a Float as well.
