### ISSUE TITLE
"<game name> memory cannot be searched due to system protections."

### ISSUE THREAD

**Issue by celakeniock** [zorgiepoo/Bit-Slicer#76]
so i got this notification
<img width="356" alt="Zrzut ekranu 2022-01-16 o 20 55 04" src="https://user-images.githubusercontent.com/49827604/149675775-7a31b479-c2d4-492a-82be-a5a6dd9f0c5b.png">

even after typing and hitting enter this command "defaults write com.zgcoder.BitSlicer ZGRemoveRootlessProcessesKey -bool NO" restarting bit slicer didnt help, Mac Monterey

**Comment by zorgiepoo** [comment]
Check the question mark button on the dialog which links to the corresponding wiki page: https://github.com/zorgiepoo/Bit-Slicer/wiki/Security-Protections . That user defaults key is unrelated.

**Comment by celakeniock** [comment]
so what should i do?

**Comment by zorgiepoo** [comment]
I'm not going to make any recommendations. You've all the information you need to make an interpretation and assessment of what to do, or should know what to look up now for further info.

**Comment by celakeniock** [comment]
i was using bit slicer before and i didnt got this problem back before, i reseted my mac to fabric settings and is not working, i heard i need to disable csrutil, but its dangerous, can you tell why it was working before or its not possible??

**Comment by zorgiepoo** [comment]
Possibly the app was updated or you were targeting a different app/game that did not have the security protections. Per disabling SIP I will refer you to [this article](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection?language=objc) which has an appropriate warning.
