### ISSUE TITLE
Support code injection for Apple Silicon

### ISSUE THREAD

**Issue by erfg12** [zorgiepoo/Bit-Slicer#77]
I noticed certain methods like `injectCode` and `bytesBeforeInjection` [don't work on "Silicon Macs"](https://github.com/zorgiepoo/Bit-Slicer/wiki/Debug-code-injection). Is there a plan in place to eventually fix this, or is it permanently broken for these devices? I'm only asking because I know Apple is making a big push this year to keep removing Intel CPU products from their product line.

**Comment by zorgiepoo** [comment]
It's not broken; code injection was just never implemented to support Apple Silicon. All the debugging functionality that landed in [1.7.11](https://github.com/zorgiepoo/Bit-Slicer/releases/tag/1.7.11) had to be implemented/ported to support arm64 architecture (1.7.10 was the first Apple Silicon build which has no debugging support).

Code injection would indeed be on the thing I'd look the next time I feel like digging in this project. In the mean time you are free to investigate how it may work on arm64. Sadly I can't find any of my notes I may have written about how it could work. If I last recall, in arm64 creating a branch island / code cave may involve overwriting and spilling more registers, which could potentially diminish its usefulness (as we have been avoiding handling cases like overwriting instructions with relative branching).

**Comment by zorgiepoo** [comment]
I've a work in progress branch (code-injection-arm64). More polish on the implementation is needed still.

To support near-jumps (+- 128 MiB) we use a branch instruction just like we use jmp on x86 (except limit for x86  is +- INT32_MAX). This is easy to implement. Unfortunately, +- 128 MiB on arm64 only suffices for the most trivial sorts of programs. But still, it's implemented in such cases.

To support far-away jumps I'm taking a newer approach of internally using breakpoints and modifying the program counter to make the jumps from/to the far-away code island. I call this approach "emulated" and it looks like a fake instruction is being added to the user. Unfortunately it looks like this approach of modifying the program counter does not bode well with Rosetta, but oh well.

I decided against trying this "natively", which would have involved sacrificing/overwriting quite a number of instructions (at least three for loading an absolute address into a register, one for preserving the register beforehand, one for doing the jump, and possibly some more to compensate jumping back to original code..)

**Comment by zorgiepoo** [comment]
Landed in [1.7.12 Alpha 1](https://github.com/zorgiepoo/Bit-Slicer/releases)
