### ISSUE TITLE
use external python or use pip of internal python

### ISSUE THREAD

**Issue by iamxujian** [zorgiepoo/Bit-Slicer#78]
great app! and i have a question about scripts...

I need some python packages installed by pip. Is there some easy way to use specific path of external python with full bit-slicer function supported? or use pip in internal python?

by the way, I tried get-pip.py to install pip for internal python, but failed...

**Comment by zorgiepoo** [comment]
Not to use another python, no, the app links and embeds its own version of python.

The app should read other external modules from `~/Application Support/Bit Slicer/Modules/`. There is code that appends that to the sys.path I think. So basically you might be able to copy Python modules from your installed packages in that directory or symlink them in. Note this has never really been tested. And I believe Bit Slicer currently uses Python 3.9.1.

**Comment by zorgiepoo** [comment]
I removed some modules like email. Random should be working though. Maybe the external stuff has to be built for python 3.9.x too, but the smaller/more pure modules you want to use the more likely you'll run into less issues. The last updated instructions for building python framework for bit slicer from source [are here](https://github.com/zorgiepoo/Bit-Slicer/blob/main/deps/python/source.txt).

**Comment by iamxujian** [comment]
interesting source.txt file. looks like bash, but not completely. I'm not familiar with x-code project, sadly.
I see the line "Remove all __pycache__ directories in Versions/3.9/lib/python3.9", and have no idea whether it runs...

I copied all __pycache__ from a normal python 3.9.1 to Bit Slicer.app to make some python function worked well for me, not only random, but also encodings such as "shift-jis". Before re-build the project, I think I need more try following this way.

and my latest error is 
`dlopen(/Applications/Bit Slicer.app/Contents/Frameworks/Python.framework/Versions/A/Resources/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Applications/Bit Slicer.app/Contents/Frameworks/Python.framework/Versions/A/Resources/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: code signature in (/Applications/Bit Slicer.app/Contents/Frameworks/Python.framework/Versions/A/Resources/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)`

I think maybe after I fix this "code signature" error, all things will work for me. :)

**Comment by zorgiepoo** [comment]
that’s a library validation issue. It will be easier if you try to build the xcode project. There are instructions somewhere on the wiki. 

The source.txt file is not a code file or anything, it’s just instructions I wrote down for how I incorporated Python.

**Comment by iamxujian** [comment]
thanks for your suggestions.
