### ISSUE TITLE
How to edit script?

### ISSUE THREAD

**Issue by U5KUN** [zorgiepoo/Bit-Slicer#89]
I can't edit script value.

https://github.com/zorgiepoo/Bit-Slicer/assets/87700116/42dc934d-ff7e-46e6-9975-995e51344d5d

**Comment by ttuleyb** [comment]
I get the same exact issue

**Comment by ttuleyb** [comment]
Yes I followed this exact guide https://github.com/zorgiepoo/Bit-Slicer/wiki/Introduction-to-Scripting#your-first-script

**Comment by ttuleyb** [comment]
The debug logs are empty:

```
03:20:29: Cleaning up..
03:20:30: Initialization..
03:20:31: Cleaning up..
03:20:31: Initialization..
03:20:51: Initialization..
```

**Comment by ttuleyb** [comment]
I'm using 1.7.12 (1152)

**Comment by ttuleyb** [comment]
Changing editor to VSCODE fixed it!

**Comment by ttuleyb** [comment]
<img width="214" alt="Screenshot 2023-08-20 at 03 31 11" src="https://github.com/zorgiepoo/Bit-Slicer/assets/74624982/c808cd64-8899-412b-b404-d45ba0ce4bdd">
One of those two

**Comment by ttuleyb** [comment]
It might be a good idea to pick literally any other editor (not textedit) because if people have them installed they usually prefer them anyways

**Comment by U5KUN** [comment]
I use IDLE too.

**Comment by ttuleyb** [comment]
It could be a good idea to warn to user to pick a different ide if edit is disabled on a script for whatever reason

**Comment by U5KUN** [comment]
can't edit script with Cursor.

**Comment by U5KUN** [comment]
CotEditor too.

**Comment by U5KUN** [comment]
I can do it with Cursor.
Open setting and change "Edit Script with".
